apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for certificate expiration notifications
    email: scarabdesign@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    # HTTP-01 challenge for domain validation
    solvers:
    - http01:
        ingress:
          class: nginx
